---
schema:
  procedures: {}
  tables:
    answer:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - answer_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - person_id
          match_type: ''
          name: answer_fk_person_id
          on_delete: CASCADE
          on_update: ''
          options: []
          reference_fields:
            - person_id
          reference_table: person
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - question_id
          match_type: ''
          name: answer_fk_question_id
          on_delete: CASCADE
          on_update: ''
          options: []
          reference_fields:
            - question_id
          reference_table: question
          type: FOREIGN KEY
      fields:
        answer_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: answer_id
          order: 1
          size:
            - 0
        content:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: content
          order: 2
          size:
            - 0
        person_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: person_id
          order: 3
          size:
            - 0
        question_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: question_id
          order: 4
          size:
            - 0
      indices:
        - fields:
            - person_id
          name: answer_idx_person_id
          options: []
          type: NORMAL
        - fields:
            - question_id
          name: answer_idx_question_id
          options: []
          type: NORMAL
      name: answer
      options: []
      order: 3
    person:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - person_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - email
          match_type: ''
          name: person_email
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - handle
          match_type: ''
          name: person_handle
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        email:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: email
          order: 3
          size:
            - 96
        handle:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: handle
          order: 2
          size:
            - 24
        password:
          data_type: char
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 4
          size:
            - 40
        person_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: person_id
          order: 1
          size:
            - 0
      indices: []
      name: person
      options: []
      order: 1
    question:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - question_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - person_id
          match_type: ''
          name: question_fk_person_id
          on_delete: CASCADE
          on_update: ''
          options: []
          reference_fields:
            - person_id
          reference_table: person
          type: FOREIGN KEY
      fields:
        asked_on:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: asked_on
          order: 4
          size:
            - 0
        details:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: details
          order: 3
          size:
            - 0
        person_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: person_id
          order: 5
          size:
            - 0
        question_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: question_id
          order: 1
          size:
            - 0
        title:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: title
          order: 2
          size:
            - 64
      indices:
        - fields:
            - person_id
          name: question_idx_person_id
          options: []
          type: NORMAL
      name: question
      options: []
      order: 2
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    package: &1 !!perl/hash:Shutterstock::Exchange::Schema
      class_mappings:
        DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult: __VERSION
        Shutterstock::Exchange::Schema::Result::Answer: Answer
        Shutterstock::Exchange::Schema::Result::Person: Person
        Shutterstock::Exchange::Schema::Result::Question: Question
      source_registrations:
        Answer: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            answer_id:
              data_type: integer
              is_auto_increment: 1
            content:
              data_type: text
            person_id:
              data_type: integer
              is_foreign_key: 1
            question_id:
              data_type: integer
              is_foreign_key: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - answer_id
            - content
            - person_id
            - question_id
          _primaries: &2
            - answer_id
          _relationships:
            person:
              attrs:
                accessor: single
                fk_columns:
                  person_id: 1
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: Shutterstock::Exchange::Schema::Result::Person
              cond:
                foreign.person_id: self.person_id
              source: Shutterstock::Exchange::Schema::Result::Person
            question:
              attrs:
                accessor: single
                fk_columns:
                  question_id: 1
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: Shutterstock::Exchange::Schema::Result::Question
              cond:
                foreign.question_id: self.question_id
              source: Shutterstock::Exchange::Schema::Result::Question
          _unique_constraints:
            primary: *2
          name: answer
          result_class: Shutterstock::Exchange::Schema::Result::Answer
          resultset_attributes: {}
          resultset_class: Shutterstock::Exchange::Schema::DefaultRS
          schema: *1
          source_name: Answer
        Person: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            email:
              data_type: varchar
              size: 96
            handle:
              data_type: varchar
              size: 24
            password:
              data_type: char
              encode_check_method: check_password
              encode_class: Digest
              encode_column: 1
              size: 40
            person_id:
              data_type: integer
              is_auto_increment: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - person_id
            - handle
            - email
            - password
          _primaries: &3
            - person_id
          _relationships:
            answer_rs:
              attrs:
                accessor: single
                cascade_delete: 1
                cascade_update: 1
                join_type: LEFT
              class: Shutterstock::Exchange::Schema::Result::Answer
              cond:
                foreign.person_id: self.person_id
              source: Shutterstock::Exchange::Schema::Result::Answer
            question_rs:
              attrs:
                accessor: single
                cascade_delete: 1
                cascade_update: 1
                join_type: LEFT
              class: Shutterstock::Exchange::Schema::Result::Question
              cond:
                foreign.person_id: self.person_id
              source: Shutterstock::Exchange::Schema::Result::Question
          _unique_constraints:
            person_email:
              - email
            person_handle:
              - handle
            primary: *3
          name: person
          result_class: Shutterstock::Exchange::Schema::Result::Person
          resultset_attributes: {}
          resultset_class: Shutterstock::Exchange::Schema::ResultSet::Person
          schema: *1
          source_name: Person
        Question: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            asked_on:
              _ic_dt_method: datetime
              _inflate_info:
                deflate: !!perl/code '{ "DUMMY" }'
                inflate: !!perl/code '{ "DUMMY" }'
              data_type: datetime
            details:
              data_type: text
            person_id:
              data_type: integer
              is_foreign_key: 1
            question_id:
              data_type: integer
              is_auto_increment: 1
            title:
              data_type: varchar
              size: 64
          _columns_info_loaded: 0
          _ordered_columns:
            - question_id
            - title
            - details
            - asked_on
            - person_id
          _primaries: &4
            - question_id
          _relationships:
            answered_by:
              attrs:
                accessor: single
                cascade_delete: 1
                cascade_update: 1
                join_type: LEFT
              class: Shutterstock::Exchange::Schema::Result::Answer
              cond:
                foreign.question_id: self.question_id
              source: Shutterstock::Exchange::Schema::Result::Answer
            person_asked_by:
              attrs:
                accessor: single
                fk_columns:
                  person_id: 1
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: Shutterstock::Exchange::Schema::Result::Person
              cond:
                foreign.person_id: self.person_id
              source: Shutterstock::Exchange::Schema::Result::Person
          _unique_constraints:
            primary: *4
          name: question
          result_class: Shutterstock::Exchange::Schema::Result::Question
          resultset_attributes: {}
          resultset_class: Shutterstock::Exchange::Schema::DefaultRS
          schema: *1
          source_name: Question
        __VERSION: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            ddl:
              data_type: text
              is_nullable: 1
            id:
              data_type: int
              is_auto_increment: 1
            upgrade_sql:
              data_type: text
              is_nullable: 1
            version:
              data_type: varchar
              size: 50
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - version
            - ddl
            - upgrade_sql
          _primaries: &5
            - id
          _relationships: {}
          _unique_constraints:
            dbix_class_deploymenthandler_versions_version:
              - version
            primary: *5
          name: dbix_class_deploymenthandler_versions
          result_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult
          resultset_attributes: {}
          resultset_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResultSet
          schema: *1
          source_name: __VERSION
      storage: !!perl/hash:DBIx::Class::Storage::DBI::SQLite
        _conn_pid: 5957
        _connect_info:
          - DBI:SQLite:/Users/johnn/Desktop/Shutterstock-Exchange/share/shutterstock-exchange-schema.db
          - ''
          - ''
        _dbh: !!perl/hash:DBI::db {}
        _dbh_autocommit: 1
        _dbh_details: {}
        _dbh_gen: 0
        _dbi_connect_info:
          - DBI:SQLite:/Users/johnn/Desktop/Shutterstock-Exchange/share/shutterstock-exchange-schema.db
          - ''
          - ''
          - &6
            AutoCommit: 1
            PrintError: 0
            RaiseError: 1
            ShowErrorStatement: 1
        _dbic_connect_attributes: *6
        _driver_determined: 1
        _in_do_block: 0
        _sql_maker: ~
        _sql_maker_opts: {}
        savepoints: []
        schema: *1
        transaction_depth: 0
    sources:
      - Person
      - Answer
      - Question
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11010
